[tool.poetry]
name = "quodlibet"
version = "4.6.0-pre"
description = "A music library, tagger, and player"
authors = ["Joe Wreschnig", "Michael Urman", "Steven Robertson",
    "Christoph Reiter", "Nick Boultbee", "(many others)"]
maintainers = ["Christoph Reiter"]
homepage = "https://quodlibet.readthedocs.io/"
documentation = "https://quodlibet.readthedocs.io/"
repository = "https://github.com/quodlibet/quodlibet"
keywords = ["audio", "music", "player", "tags", "gtk"]
license = "GPL-2.0-or-later"

packages = [
    { include = "quodlibet", from = "." }
]

[tool.poetry.scripts]
# Convenience: `poetry run quodlibet` just runs the app (with no CLI args)
quodlibet = "quodlibet.main:main"


[tool.poetry.dependencies]
python = "^3.8"
mutagen = "^1.45"
feedparser = "^5.2 || ^6.0"
pycairo = "^1.19"
pygobject = "^3.34.0"
# Optional (mainly plugins)
musicbrainzngs = { version = "0.*", optional = true }
dbus-python = { version = "*", optional = true }
soco = { version = "^0.22.2", optional = true }
pypresence = { version = "^4.2.1", optional = true }

[tool.poetry.extras]
# Use with poetry install -E plugins
plugins = ["musicbrainzngs", "pyinotify", "dbus-python", "paho-mqtt", "soco", "pypresence"]

[tool.poetry.dev-dependencies]
pytest = '^7.1.1'
polib = '^1.1.0'
sphinx = '^5.0.2'
sphinx_rtd_theme = '^1.0.0'
sphinx-autobuild = "^2021.3.14"
xvfbwrapper = { version = "^0.2", platform = "linux" }
flake8 = "^4.0.1"
coverage = { extras = ["toml"], version = "^6.3.2" }
mypy = "^0.971"
flaky = "^3.7.0"
types-docutils = "^0.19.0"
types-certifi = "^2021.10.8"
types-requests = "^2.27.15"

[tool.coverage.run]
omit = ["quodlibet/packages/*"]
include = ["quodlibet/*"]

[build-system]
requires = ["setuptools", "wheel"]
